services:
  broker:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr=PLAINTEXT://broker:9092,OUTSIDE://localhost:29092
    ports: ["29092:29092"]

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prbot
    ports: ["5434:5432"]

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    depends_on: [broker, db]
    ports: ["8000:8000"]
    volumes:
      - ./secrets:/app/secrets:ro

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    depends_on: [broker, db]
    volumes:
      - ./secrets:/worker/secrets:ro
